cd Libs\Library\ButiBulletWrap\
git pull
cd ..\ButiScript\
git pull
cd ..\ButiMemorySystem\
git pull
cd ..\ButiUtil\
git pull
cd ..\ButiMath\
git pull
cd ..\ButiEventSystem\
git pull
cd ..\ButiFont\
git pull
cd ..\ButiRendering_Dx12\
git pull
cd ..\ButiEngineHeader\
git pull
cd ..\..\
pause